<?xml version="1.0" encoding="UTF-8"?>
<call>
   <metadata>
      <row>
         <version>12.2.0</version>
      </row>
   </metadata>
   <general_attributes>
      <row>
         <minimum_ae_version>11.2</minimum_ae_version>
         <auto_deactivation>A</auto_deactivation>
         <child_flags>00000000000000000000000000000000</child_flags>
         <last_runtimes>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</last_runtimes>
         <max_parallel_action>1</max_parallel_action>
         <mrt_time>000000</mrt_time>
         <name>PCK.AUTOMIC_ANALYTICS.PRV.CALL.GET_SHARED_ERROR</name>
         <type>CALL</type>
         <inherit_output_filter>N</inherit_output_filter>
         <queue>CLIENT_QUEUE</queue>
         <sub_type>1</sub_type>
         <description>Executed when a request to the backend fails to inform the user</description>
         <versioning_id>1450836043</versioning_id>
      </row>
   </general_attributes>
   <scripts>
      <row>
         <process><![CDATA[:ADD_ATT RECIPIENT, "&$USER#/&$DEPARTMENT#"
!get error from report
:SET &ERROR# = "Unknown"
:SET &HND# = PREP_PROCESS_REPORT(,&$ACTIVATOR_RUNID#,"REP","Error:*","COL=DELIMITER", "DELIMITER=*Error:*")
:PROCESS &HND#
:   SET  &ERROR# = GET_PROCESS_LINE(&HND#,2)
:   PRINT "Error: &ERROR#"
:ENDPROCESS
:CLOSE_PROCESS &HND#]]></process>
      </row>
   </scripts>
   <notification_attributes>
      <row>
         <priority>2</priority>
         <subject>Error requesting data from the analytics backend</subject>
         <content><![CDATA[Error: &ERROR#

Please check the report of &$ACTIVATOR# with the run id: &$ACTIVATOR_RUNID# to get the error details.

Make sure the analytics agent is able to connect to the analytics backend and that all other connection settings when executing PCK.AUTOMIC_ANALYTICS.PUB.ACTION.ANALYTICS_CONFIGURATION are valid.

]]></content>
      </row>
   </notification_attributes>
   <rollback_definitions>
      <row>
      </row>
   </rollback_definitions>
</call>
